name: comfyui
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python>=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip:
    # comfyui requirements
    - einops
    - transformers>=4.25.1
    - safetensors>=0.4.2
    - aiohttp
    - pyyaml
    - Pillow
    - scipy
    - tqdm
    - psutil
    # comfy-action requirements
    - requests
    - google-cloud-storage
    - comfy-cli
    - charset-normalizer