name: "Windows Release packaging"

on:
  workflow_dispatch:
    inputs:
      cu:
        description: 'cuda version'
        required: true
        type: string
        default: "121"

      python_minor:
        description: 'python minor version'
        required: true
        type: string
        default: "11"

      python_patch:
        description: 'python patch version'
        required: true
        type: string
        default: "6"
#  push:
#    branches:
#      - master

jobs:
  package_ccniyui:
    permissions:
        contents: "write"
        packages: "write"
        pull-requests: "read"
    runs-on: windows-latest
    steps:
        - uses: actions/cache/restore@v3
          id: cache
          with:
            path: |
              cu${{ inputs.cu }}_python_deps.tar
              update_ccniyui_and_python_dependencies.bat
            key: ${{ runner.os }}-build-cu${{ inputs.cu }}-${{ inputs.python_minor }}
        - shell: bash
          run: |
            mv cu${{ inputs.cu }}_python_deps.tar ../
            mv update_ccniyui_and_python_dependencies.bat ../
            cd ..
            tar xf cu${{ inputs.cu }}_python_deps.tar
            pwd
            ls

        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
            persist-credentials: false
        - shell: bash
          run: |
            cd ..
            cp -r ccniyUI ccniyUI_copy
            curl https://www.python.org/ftp/python/3.${{ inputs.python_minor }}.${{ inputs.python_patch }}/python-3.${{ inputs.python_minor }}.${{ inputs.python_patch }}-embed-amd64.zip -o python_embeded.zip
            unzip python_embeded.zip -d python_embeded
            cd python_embeded
            echo 'import site' >> ./python3${{ inputs.python_minor }}._pth
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            ./python.exe get-pip.py
            ./python.exe -s -m pip install ../cu${{ inputs.cu }}_python_deps/*
            sed -i '1i../ccniyUI' ./python3${{ inputs.python_minor }}._pth
            cd ..

            git clone https://github.com/ccniyanonymous/taesd
            cp taesd/*.pth ./ccniyUI_copy/models/vae_approx/

            mkdir ccniyUI_windows_portable
            mv python_embeded ccniyUI_windows_portable
            mv ccniyUI_copy ccniyUI_windows_portable/ccniyUI

            cd ccniyUI_windows_portable

            mkdir update
            cp -r ccniyUI/.ci/update_windows/* ./update/
            cp -r ccniyUI/.ci/windows_base_files/* ./
            cp ../update_ccniyui_and_python_dependencies.bat ./update/

            cd ..

            "C:\Program Files\7-Zip\7z.exe" a -t7z -m0=lzma -mx=8 -mfb=64 -md=32m -ms=on -mf=BCJ2 ccniyUI_windows_portable.7z ccniyUI_windows_portable
            mv ccniyUI_windows_portable.7z ccniyUI/new_ccniyUI_windows_portable_nvidia_cu${{ inputs.cu }}_or_cpu.7z

            cd ccniyUI_windows_portable
            python_embeded/python.exe -s ccniyUI/main.py --quick-test-for-ci --cpu

            ls

        - name: Upload binaries to release
          uses: svenstaro/upload-release-action@v2
          with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: new_ccniyUI_windows_portable_nvidia_cu${{ inputs.cu }}_or_cpu.7z
                tag: "latest"
                overwrite: true

