name: "Windows Release cu118 dependencies 2"

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master

jobs:
  build_dependencies:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10.9'

        - shell: bash
          run: |
            python -m pip wheel --no-cache-dir torch torchvision torchaudio xformers --extra-index-url https://download.pytorch.org/whl/cu118 -r requirements.txt pygit2 -w ./temp_wheel_dir
            python -m pip install --no-cache-dir ./temp_wheel_dir/*
            echo installed basic
            ls -lah temp_wheel_dir
            mv temp_wheel_dir cu118_python_deps
            tar cf cu118_python_deps.tar cu118_python_deps

        - uses: actions/cache/save@v3
          with:
            path: cu118_python_deps.tar
            key: ${{ runner.os }}-build-cu118
